FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 파일들을 컨테이너에 복사
COPY main.py /app/main.py
COPY api/ /app/api/
COPY models/ /app/models/
COPY langchain.py /app/langchain.py
COPY .env /app/.env
COPY requirements.txt /app/requirements.txt

# 필요한 라이브러리 설치
RUN pip install -r requirements.txt

# FastAPI 앱 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001"]