spring:
  profiles:
    active:
      - local
    group:
      local:
        - rabbitmq-local
      prod:
        - rabbitmq-prod
      dev:
        - rabbitmq-dev
    include:
      - rabbitmq


server:
  port: 8001

logging:
  level:
    org:
      springframework: info


rabbitmq:
  exchange:
    name: image-creation-exchange
    type: direct

  queue:
    request:
      name: image-creation-request-queue
      routing-key: image.creation.request
    response:
      name: image-creation-response-queue
      routing-key: image.creation.response

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}