spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      prod:
        - db-dev
    include:
      - oauth
      - db
# RabbitMQ 연결 정보
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 8001

logging:
  level:
    org:
      springframework: info


rabbitmq:
  exchange:
    name: image-creation-exchange
    type: direct

  queue:
    request:
      name: image-creation-request-queue
      routing-key: image.creation.request
    response:
      name: image-creation-response-queue
      routing-key: image.creation.response
