spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: 5259e8e054d186bbde75ddd66650a767
            client-secret: V20WmcBB6Jygxci1KqeKnl42UrHNwUtp
            scope: profile_nickname, account_email
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id