#default 공통설정
spring:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: MYSQL
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database-platform: H2
  datasource:
    url: jdbc:h2:tcp://localhost/~/dreamgream
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379


--- # prod 설정
spring:
  config:
    activate:
      on-profile: "db-dev"
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://localhost:3306/dreamgream?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

