#default 공통설정
spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      hibernate.format_sql: true
      hibernate.show_sql: false

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database-platform: H2
  datasource:
    url: jdbc:h2:tcp://localhost/~/dreamgream
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

--- # local mysql 설정
spring:
  config:
    activate:
      on-profile: "db-local-mysql"
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dreamgream?characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  sql:
    init:
      mode: always

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "db-dev"
  data:
    redis:
      host: ssafy-redis-dev
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafya609
    url: jdbc:mysql://ssafy-db:3306/dreamgreamdev?characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  sql:
    init:
      mode: always

--- # prod 설정
spring:
  config:
    activate:
      on-profile: "db-prod"
  data:
    redis:
      host: ssafy-redis
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafya609
    url: jdbc:mysql://ssafy-db:3306/dreamgream?characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true

